# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171203_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 4, 11, 24, 24, 320358)),
        ),
    ]
